[package]
name = "dfu"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = "1.0.1"
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
